baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[taxonomies]
  tag = "tags"
  category = "categories"
  year = "year"
	month = "month"

[outputs]
    home = [ "HTML", "JSON", "RSS"]

[params]
snipcart_test_api_key = "ZDhjMjA2ZWUtNzY4Ny00YTc0LThmYmYtYWRjM2QyZDcwZDlmNjM4MDIyNzY5NjY2NTU2ODEw"
snipcart_live_api_key = ""